### ISSUE TITLE
Nome semântico para o método

### ISSUE THREAD

**Issue by edysegura** [DanielaMara/php-converter-temperatura#1]
Oi Daniela!

O que você acha de alterar o nome do método do link abaixo para um nome mais semântico?
https://github.com/DanielaMara/php-converter-temperatura/blob/master/service/ConverterService.class.php#L4

**Comment by DanielaMara** [comment]
Olá Edy, segui sua sugestão e alterei o nome do método.
Gostaria que avaliasse se assim está melhor.
https://github.com/DanielaMara/php-converter-temperatura/blob/master/service/ConverterService.class.php#L4

**Comment by edysegura** [comment]
Bem melhor @DanielaMara!!!! ;)
